name: qaribu

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - qaribu_mobile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get Packages
        run: flutter pub get
      - name: Build APK
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_JKS_PASSWORD: ${{ secrets.KEY_JKS_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        run: base64 -d <<< $KEY_JKS > ./android/app/upload-keystore.jks && flutter build apk -t lib/main_development.dart --flavor development
      - name: Upload APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-development-release.apk"
          tag: v1.0.2
          token: ${{ secrets.TOKEN }}

  
